name: .NET Framework Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Restore packages
      run: dotnet restore

    # - name: Add sln
    #   run: dotnet sln add ./MyApp.Tests/MyApp.Test.csproj

    # - name: Add References
    #   run: dotnet add ./MyApp.Tests/MyApp.Test.csproj reference ./MyApp/MyApp.csproj

    # - name: Cleaning
    #   run: dotnet clean

    - name: Build solution
      run: dotnet build .\MyApp\MyApp.csproj

    - name: Change Directory
      run: cd .\MyApp.Tests

    - name: Run Tests
      run: dotnet test


# name: .NET Framework Workflow

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build-and-test:
#     runs-on: windows-2019

#     steps:
#     - uses: actions/checkout@v2

#     - name: Setup MSBuild path
#       uses: microsoft/setup-msbuild@v1

#     - name: Setup VSTest
#       uses: darenm/Setup-VSTest@v1

#     - name: Restore NuGet packages
#       run: msbuild -t:restore -p:Configuration=Debug

#     - name: Build solution
#       run: msbuild -p:Configuration=Debug

#     - name: Run Tests
#       run: vstest.console.exe .\MyApp.Tests\bin\Debug\MyApp.Tests.dll
