name: .NET Framework Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild -t:restore -p:Configuration=Release

    - name: Build solution
      run: msbuild -p:Configuration=Release

    - name: Test solution
      run: msbuild -t:VSTest -p:Configuration=Release

# name: .NET Framework Workflow

# on:  
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:  
#   build:    
#     runs-on: windows-2019
    
#     steps:      
#       - uses: actions/checkout@v2
      
#       - name: Setup MSBuild
#         uses: microsoft/setup-msbuild@v1

#       - name: Setup NuGet
#         uses: NuGet/setup-nuget@v1.0.5
        
#       - name: Setup VSTest
#         uses: darenm/Setup-VSTest@v1

#       - name: Navigate to Workspace
#         run: cd $GITHUB_WORKSPACE

#       - name: Restore Packages
#         run: nuget restore solution.sln

#       - name: Build Solution
#         run: |
#           msbuild.exe solution.sln /p:platform="Any CPU" /p:configuration="Release"
        
#       - name: Run Tests
#         run: vstest.console.exe .\tests\MyApp.Tests\bin\Release\MyApp.Tests.dll