name: .NET Framework Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with .NET Core CLI
      run: dotnet build --configuration Release

    - name: Test with .NET Core CLI
      run: dotnet test --configuration Release --no-build

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build-and-test:
#     runs-on: windows-2019

#     steps:
#     - uses: actions/checkout@v2

#     - name: Setup MSBuild path
#       uses: microsoft/setup-msbuild@v1

#     - name: Setup VSTest
#       uses: darenm/Setup-VSTest@v1

#     - name: Restore NuGet packages
#       run: msbuild -t:restore -p:Configuration=Release

#     - name: Build solution
#       run: msbuild -p:Configuration=Release

#     - name: Run Tests
#       run: vstest.console.exe .\MyApp.Tests\bin\Release\MyApp.Tests.dll
