name: .NET Framework Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        arguments: '--configuration Release --no-build'